# Base Image
FROM	python:3.6.5-alpine


# Setting working directory
WORKDIR	/app


# Install Dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd && \
    apk add libffi-dev


# Dealing with requirements
COPY ./requirements.txt /app/requirements.txt
RUN pip	install	-r	requirements.txt


#	add	entrypoint.sh
COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh


# Coping project
COPY . /app


# Running server
CMD python manage.py run -h 0.0.0.0