"""empty message

Revision ID: 0814d285b306
Revises: 13f0a331195b
Create Date: 2018-11-26 15:42:42.229106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0814d285b306'
down_revision = '13f0a331195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
