"""empty message

Revision ID: 2b842d8cfc3e
Revises: 
Create Date: 2018-11-19 00:09:28.651218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b842d8cfc3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('teste', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
